os: osx
osx_image: xcode8
before_install:
  - ./dev/script/get-aux-repo
  - brew update
  - brew tap project-renard/project-renard
install:
  - export BASE_DIR=`cd project-renard/travis-homebrew-bottle && pwd`; echo "$BASE_DIR"
  - ( cat $BASE_DIR/Project-Renard-base.tgz.part.* > ~/Project-Renard-base.tgz &&
      mkdir /Applications/Project-Renard.app && cd /Applications/Project-Renard.app && tar xzf ~/Project-Renard-base.tgz )
  - ( cd dev/ci && ./build-dmg.sh --steps build-only-non-deps --steps postinstall )
  - ( cd dev/ci && travis_wait 30 ./build-dmg.sh --steps dmg )
script:
  - du -h ~/ProjectRenard-Installer.dmg
deploy:
  provider: releases
  api_key:
    secure: pDzl4TttrSyDaayLAC7+l7Vrcmbe0Q5nWGomoILqxQhA1j/HtesLlkJAtbuajx+DNTia7tBbTljlCvoucYgyUxwm9gKss3NFweKlFYryE6XfeXuDkNe7BqZxGhlhpSN/0c8cPn7Dr49Yk3yMdeYU8uWE3Jz317db26Uhnw5D+CdtGtb2KlZM9JMy0hGSZaCCA+GXxcVkvXS5OEERCc/5UM0bmQO8+uwYBIok2K5eY5syeCcw4L+APF5G1zvcMRJxOfFm60pKOLTaC+70AxdjnOyfO+e65W3Kbyf4usTLcHUt4JWOPOd6BGmNyaKeEs+nrb3HW6xFsyoI9TB8cWR7OCwh1CITN5Ww46pXVG+ckFHRVTPBqc3nwPLrCp9VajBMDUod6yu5XIr/sGRTsvIJCY5NCOOrl4iFObp47ic1+uaBRnUqJHPRLUCJrb0+Sf1XnvuCkAjWrkYnaNLbKl6bqIHbm/zTn9XezM4ZP5gKnmdXQ+Mn52G0F8+mh63G4W04s+agizj895jMflccp7AxqnN/Q/5IEPQcHD6DDc/82LQu0joErzg24qWyBsTOe+mVWGHwYLZBaBZ9aJ7o14VGrBYfuqcMO5HNbYWxc4z3Ikr/DqMVug/vIwxJ6Xa82ozChXEpr26NX2GwF7JsJeBRAB0KyRaSQYdWiZNiZWhtZ4I=
  file: ${HOME}/ProjectRenard-Installer.dmg
  on:
    repo: project-renard/release
  overwrite: true
